/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PharmaciesRouteImport } from './routes/pharmacies'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MapRouteImport } from './routes/map'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as DonorsRouteImport } from './routes/donors'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AddPharmacyRouteImport } from './routes/add-pharmacy'
import { Route as AddHospitalRouteImport } from './routes/add-hospital'
import { Route as AddEquipmentRouteImport } from './routes/add-equipment'
import { Route as AddDonorRouteImport } from './routes/add-donor'
import { Route as AddDoctorRouteImport } from './routes/add-doctor'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as DoctorsIdRouteImport } from './routes/doctors.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmaciesRoute = PharmaciesRouteImport.update({
  id: '/pharmacies',
  path: '/pharmacies',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorsRoute = DonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPharmacyRoute = AddPharmacyRouteImport.update({
  id: '/add-pharmacy',
  path: '/add-pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AddHospitalRoute = AddHospitalRouteImport.update({
  id: '/add-hospital',
  path: '/add-hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const AddEquipmentRoute = AddEquipmentRouteImport.update({
  id: '/add-equipment',
  path: '/add-equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const AddDonorRoute = AddDonorRouteImport.update({
  id: '/add-donor',
  path: '/add-donor',
  getParentRoute: () => rootRouteImport,
} as any)
const AddDoctorRoute = AddDoctorRouteImport.update({
  id: '/add-doctor',
  path: '/add-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIdRoute = DoctorsIdRouteImport.update({
  id: '/doctors/$id',
  path: '/doctors/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/add-doctor': typeof AddDoctorRoute
  '/add-donor': typeof AddDonorRoute
  '/add-equipment': typeof AddEquipmentRoute
  '/add-hospital': typeof AddHospitalRoute
  '/add-pharmacy': typeof AddPharmacyRoute
  '/auth': typeof AuthRoute
  '/donors': typeof DonorsRoute
  '/equipment': typeof EquipmentRoute
  '/home': typeof HomeRoute
  '/hospitals': typeof HospitalsRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pharmacies': typeof PharmaciesRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/doctors/': typeof DoctorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/add-doctor': typeof AddDoctorRoute
  '/add-donor': typeof AddDonorRoute
  '/add-equipment': typeof AddEquipmentRoute
  '/add-hospital': typeof AddHospitalRoute
  '/add-pharmacy': typeof AddPharmacyRoute
  '/auth': typeof AuthRoute
  '/donors': typeof DonorsRoute
  '/equipment': typeof EquipmentRoute
  '/home': typeof HomeRoute
  '/hospitals': typeof HospitalsRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pharmacies': typeof PharmaciesRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/doctors': typeof DoctorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/add-doctor': typeof AddDoctorRoute
  '/add-donor': typeof AddDonorRoute
  '/add-equipment': typeof AddEquipmentRoute
  '/add-hospital': typeof AddHospitalRoute
  '/add-pharmacy': typeof AddPharmacyRoute
  '/auth': typeof AuthRoute
  '/donors': typeof DonorsRoute
  '/equipment': typeof EquipmentRoute
  '/home': typeof HomeRoute
  '/hospitals': typeof HospitalsRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pharmacies': typeof PharmaciesRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/doctors/': typeof DoctorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/add-doctor'
    | '/add-donor'
    | '/add-equipment'
    | '/add-hospital'
    | '/add-pharmacy'
    | '/auth'
    | '/donors'
    | '/equipment'
    | '/home'
    | '/hospitals'
    | '/map'
    | '/notifications'
    | '/onboarding'
    | '/pharmacies'
    | '/profile'
    | '/search'
    | '/settings'
    | '/doctors/$id'
    | '/doctors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/add-doctor'
    | '/add-donor'
    | '/add-equipment'
    | '/add-hospital'
    | '/add-pharmacy'
    | '/auth'
    | '/donors'
    | '/equipment'
    | '/home'
    | '/hospitals'
    | '/map'
    | '/notifications'
    | '/onboarding'
    | '/pharmacies'
    | '/profile'
    | '/search'
    | '/settings'
    | '/doctors/$id'
    | '/doctors'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/add-doctor'
    | '/add-donor'
    | '/add-equipment'
    | '/add-hospital'
    | '/add-pharmacy'
    | '/auth'
    | '/donors'
    | '/equipment'
    | '/home'
    | '/hospitals'
    | '/map'
    | '/notifications'
    | '/onboarding'
    | '/pharmacies'
    | '/profile'
    | '/search'
    | '/settings'
    | '/doctors/$id'
    | '/doctors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AddDoctorRoute: typeof AddDoctorRoute
  AddDonorRoute: typeof AddDonorRoute
  AddEquipmentRoute: typeof AddEquipmentRoute
  AddHospitalRoute: typeof AddHospitalRoute
  AddPharmacyRoute: typeof AddPharmacyRoute
  AuthRoute: typeof AuthRoute
  DonorsRoute: typeof DonorsRoute
  EquipmentRoute: typeof EquipmentRoute
  HomeRoute: typeof HomeRoute
  HospitalsRoute: typeof HospitalsRoute
  MapRoute: typeof MapRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PharmaciesRoute: typeof PharmaciesRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  DoctorsIdRoute: typeof DoctorsIdRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacies': {
      id: '/pharmacies'
      path: '/pharmacies'
      fullPath: '/pharmacies'
      preLoaderRoute: typeof PharmaciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donors': {
      id: '/donors'
      path: '/donors'
      fullPath: '/donors'
      preLoaderRoute: typeof DonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-pharmacy': {
      id: '/add-pharmacy'
      path: '/add-pharmacy'
      fullPath: '/add-pharmacy'
      preLoaderRoute: typeof AddPharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-hospital': {
      id: '/add-hospital'
      path: '/add-hospital'
      fullPath: '/add-hospital'
      preLoaderRoute: typeof AddHospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-equipment': {
      id: '/add-equipment'
      path: '/add-equipment'
      fullPath: '/add-equipment'
      preLoaderRoute: typeof AddEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-donor': {
      id: '/add-donor'
      path: '/add-donor'
      fullPath: '/add-donor'
      preLoaderRoute: typeof AddDonorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-doctor': {
      id: '/add-doctor'
      path: '/add-doctor'
      fullPath: '/add-doctor'
      preLoaderRoute: typeof AddDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$id': {
      id: '/doctors/$id'
      path: '/doctors/$id'
      fullPath: '/doctors/$id'
      preLoaderRoute: typeof DoctorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AddDoctorRoute: AddDoctorRoute,
  AddDonorRoute: AddDonorRoute,
  AddEquipmentRoute: AddEquipmentRoute,
  AddHospitalRoute: AddHospitalRoute,
  AddPharmacyRoute: AddPharmacyRoute,
  AuthRoute: AuthRoute,
  DonorsRoute: DonorsRoute,
  EquipmentRoute: EquipmentRoute,
  HomeRoute: HomeRoute,
  HospitalsRoute: HospitalsRoute,
  MapRoute: MapRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PharmaciesRoute: PharmaciesRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  DoctorsIdRoute: DoctorsIdRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
