/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PharmaciesRouteImport } from './routes/pharmacies'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OnCallPharmaciesRouteImport } from './routes/on-call-pharmacies'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NearbyDoctorsRouteImport } from './routes/nearby-doctors'
import { Route as MapRouteImport } from './routes/map'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as DonorsRouteImport } from './routes/donors'
import { Route as CivilProtectionRouteImport } from './routes/civil-protection'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AddPharmacyRouteImport } from './routes/add-pharmacy'
import { Route as AddOnCallPharmacyRouteImport } from './routes/add-on-call-pharmacy'
import { Route as AddLabRouteImport } from './routes/add-lab'
import { Route as AddHospitalRouteImport } from './routes/add-hospital'
import { Route as AddEquipmentRouteImport } from './routes/add-equipment'
import { Route as AddDonorRouteImport } from './routes/add-donor'
import { Route as AddDoctorRouteImport } from './routes/add-doctor'
import { Route as AddCivilProtectionRouteImport } from './routes/add-civil-protection'
import { Route as AddCharityRouteImport } from './routes/add-charity'
import { Route as AddBloodRequestRouteImport } from './routes/add-blood-request'
import { Route as AddAmbulanceRouteImport } from './routes/add-ambulance'
import { Route as AddRouteImport } from './routes/add'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as PharmaciesIdRouteImport } from './routes/pharmacies.$id'
import { Route as DoctorsIdRouteImport } from './routes/doctors.$id'
import { Route as AuthenticatedManageRouteImport } from './routes/_authenticated/manage'
import { Route as AuthenticatedManageIndexRouteImport } from './routes/_authenticated/manage.index'
import { Route as AuthenticatedManageSubmissionsRouteImport } from './routes/_authenticated/manage.submissions'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmaciesRoute = PharmaciesRouteImport.update({
  id: '/pharmacies',
  path: '/pharmacies',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OnCallPharmaciesRoute = OnCallPharmaciesRouteImport.update({
  id: '/on-call-pharmacies',
  path: '/on-call-pharmacies',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyDoctorsRoute = NearbyDoctorsRouteImport.update({
  id: '/nearby-doctors',
  path: '/nearby-doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorsRoute = DonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => rootRouteImport,
} as any)
const CivilProtectionRoute = CivilProtectionRouteImport.update({
  id: '/civil-protection',
  path: '/civil-protection',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPharmacyRoute = AddPharmacyRouteImport.update({
  id: '/add-pharmacy',
  path: '/add-pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AddOnCallPharmacyRoute = AddOnCallPharmacyRouteImport.update({
  id: '/add-on-call-pharmacy',
  path: '/add-on-call-pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AddLabRoute = AddLabRouteImport.update({
  id: '/add-lab',
  path: '/add-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AddHospitalRoute = AddHospitalRouteImport.update({
  id: '/add-hospital',
  path: '/add-hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const AddEquipmentRoute = AddEquipmentRouteImport.update({
  id: '/add-equipment',
  path: '/add-equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const AddDonorRoute = AddDonorRouteImport.update({
  id: '/add-donor',
  path: '/add-donor',
  getParentRoute: () => rootRouteImport,
} as any)
const AddDoctorRoute = AddDoctorRouteImport.update({
  id: '/add-doctor',
  path: '/add-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AddCivilProtectionRoute = AddCivilProtectionRouteImport.update({
  id: '/add-civil-protection',
  path: '/add-civil-protection',
  getParentRoute: () => rootRouteImport,
} as any)
const AddCharityRoute = AddCharityRouteImport.update({
  id: '/add-charity',
  path: '/add-charity',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBloodRequestRoute = AddBloodRequestRouteImport.update({
  id: '/add-blood-request',
  path: '/add-blood-request',
  getParentRoute: () => rootRouteImport,
} as any)
const AddAmbulanceRoute = AddAmbulanceRouteImport.update({
  id: '/add-ambulance',
  path: '/add-ambulance',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmaciesIdRoute = PharmaciesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PharmaciesRoute,
} as any)
const DoctorsIdRoute = DoctorsIdRouteImport.update({
  id: '/doctors/$id',
  path: '/doctors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedManageRoute = AuthenticatedManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManageIndexRoute =
  AuthenticatedManageIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedManageRoute,
  } as any)
const AuthenticatedManageSubmissionsRoute =
  AuthenticatedManageSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedManageRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/add-ambulance': typeof AddAmbulanceRoute
  '/add-blood-request': typeof AddBloodRequestRoute
  '/add-charity': typeof AddCharityRoute
  '/add-civil-protection': typeof AddCivilProtectionRoute
  '/add-doctor': typeof AddDoctorRoute
  '/add-donor': typeof AddDonorRoute
  '/add-equipment': typeof AddEquipmentRoute
  '/add-hospital': typeof AddHospitalRoute
  '/add-lab': typeof AddLabRoute
  '/add-on-call-pharmacy': typeof AddOnCallPharmacyRoute
  '/add-pharmacy': typeof AddPharmacyRoute
  '/auth': typeof AuthRoute
  '/civil-protection': typeof CivilProtectionRoute
  '/donors': typeof DonorsRoute
  '/equipment': typeof EquipmentRoute
  '/home': typeof HomeRoute
  '/hospitals': typeof HospitalsRoute
  '/map': typeof MapRoute
  '/nearby-doctors': typeof NearbyDoctorsRoute
  '/notifications': typeof NotificationsRoute
  '/on-call-pharmacies': typeof OnCallPharmaciesRoute
  '/onboarding': typeof OnboardingRoute
  '/pharmacies': typeof PharmaciesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/manage': typeof AuthenticatedManageRouteWithChildren
  '/doctors/$id': typeof DoctorsIdRoute
  '/pharmacies/$id': typeof PharmaciesIdRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/manage/submissions': typeof AuthenticatedManageSubmissionsRoute
  '/manage/': typeof AuthenticatedManageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/add-ambulance': typeof AddAmbulanceRoute
  '/add-blood-request': typeof AddBloodRequestRoute
  '/add-charity': typeof AddCharityRoute
  '/add-civil-protection': typeof AddCivilProtectionRoute
  '/add-doctor': typeof AddDoctorRoute
  '/add-donor': typeof AddDonorRoute
  '/add-equipment': typeof AddEquipmentRoute
  '/add-hospital': typeof AddHospitalRoute
  '/add-lab': typeof AddLabRoute
  '/add-on-call-pharmacy': typeof AddOnCallPharmacyRoute
  '/add-pharmacy': typeof AddPharmacyRoute
  '/auth': typeof AuthRoute
  '/civil-protection': typeof CivilProtectionRoute
  '/donors': typeof DonorsRoute
  '/equipment': typeof EquipmentRoute
  '/home': typeof HomeRoute
  '/hospitals': typeof HospitalsRoute
  '/map': typeof MapRoute
  '/nearby-doctors': typeof NearbyDoctorsRoute
  '/notifications': typeof NotificationsRoute
  '/on-call-pharmacies': typeof OnCallPharmaciesRoute
  '/onboarding': typeof OnboardingRoute
  '/pharmacies': typeof PharmaciesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/pharmacies/$id': typeof PharmaciesIdRoute
  '/doctors': typeof DoctorsIndexRoute
  '/manage/submissions': typeof AuthenticatedManageSubmissionsRoute
  '/manage': typeof AuthenticatedManageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/add': typeof AddRoute
  '/add-ambulance': typeof AddAmbulanceRoute
  '/add-blood-request': typeof AddBloodRequestRoute
  '/add-charity': typeof AddCharityRoute
  '/add-civil-protection': typeof AddCivilProtectionRoute
  '/add-doctor': typeof AddDoctorRoute
  '/add-donor': typeof AddDonorRoute
  '/add-equipment': typeof AddEquipmentRoute
  '/add-hospital': typeof AddHospitalRoute
  '/add-lab': typeof AddLabRoute
  '/add-on-call-pharmacy': typeof AddOnCallPharmacyRoute
  '/add-pharmacy': typeof AddPharmacyRoute
  '/auth': typeof AuthRoute
  '/civil-protection': typeof CivilProtectionRoute
  '/donors': typeof DonorsRoute
  '/equipment': typeof EquipmentRoute
  '/home': typeof HomeRoute
  '/hospitals': typeof HospitalsRoute
  '/map': typeof MapRoute
  '/nearby-doctors': typeof NearbyDoctorsRoute
  '/notifications': typeof NotificationsRoute
  '/on-call-pharmacies': typeof OnCallPharmaciesRoute
  '/onboarding': typeof OnboardingRoute
  '/pharmacies': typeof PharmaciesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/_authenticated/manage': typeof AuthenticatedManageRouteWithChildren
  '/doctors/$id': typeof DoctorsIdRoute
  '/pharmacies/$id': typeof PharmaciesIdRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/_authenticated/manage/submissions': typeof AuthenticatedManageSubmissionsRoute
  '/_authenticated/manage/': typeof AuthenticatedManageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/add-ambulance'
    | '/add-blood-request'
    | '/add-charity'
    | '/add-civil-protection'
    | '/add-doctor'
    | '/add-donor'
    | '/add-equipment'
    | '/add-hospital'
    | '/add-lab'
    | '/add-on-call-pharmacy'
    | '/add-pharmacy'
    | '/auth'
    | '/civil-protection'
    | '/donors'
    | '/equipment'
    | '/home'
    | '/hospitals'
    | '/map'
    | '/nearby-doctors'
    | '/notifications'
    | '/on-call-pharmacies'
    | '/onboarding'
    | '/pharmacies'
    | '/profile'
    | '/search'
    | '/settings'
    | '/manage'
    | '/doctors/$id'
    | '/pharmacies/$id'
    | '/doctors/'
    | '/manage/submissions'
    | '/manage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/add-ambulance'
    | '/add-blood-request'
    | '/add-charity'
    | '/add-civil-protection'
    | '/add-doctor'
    | '/add-donor'
    | '/add-equipment'
    | '/add-hospital'
    | '/add-lab'
    | '/add-on-call-pharmacy'
    | '/add-pharmacy'
    | '/auth'
    | '/civil-protection'
    | '/donors'
    | '/equipment'
    | '/home'
    | '/hospitals'
    | '/map'
    | '/nearby-doctors'
    | '/notifications'
    | '/on-call-pharmacies'
    | '/onboarding'
    | '/pharmacies'
    | '/profile'
    | '/search'
    | '/settings'
    | '/doctors/$id'
    | '/pharmacies/$id'
    | '/doctors'
    | '/manage/submissions'
    | '/manage'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/add'
    | '/add-ambulance'
    | '/add-blood-request'
    | '/add-charity'
    | '/add-civil-protection'
    | '/add-doctor'
    | '/add-donor'
    | '/add-equipment'
    | '/add-hospital'
    | '/add-lab'
    | '/add-on-call-pharmacy'
    | '/add-pharmacy'
    | '/auth'
    | '/civil-protection'
    | '/donors'
    | '/equipment'
    | '/home'
    | '/hospitals'
    | '/map'
    | '/nearby-doctors'
    | '/notifications'
    | '/on-call-pharmacies'
    | '/onboarding'
    | '/pharmacies'
    | '/profile'
    | '/search'
    | '/settings'
    | '/_authenticated/manage'
    | '/doctors/$id'
    | '/pharmacies/$id'
    | '/doctors/'
    | '/_authenticated/manage/submissions'
    | '/_authenticated/manage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AddRoute: typeof AddRoute
  AddAmbulanceRoute: typeof AddAmbulanceRoute
  AddBloodRequestRoute: typeof AddBloodRequestRoute
  AddCharityRoute: typeof AddCharityRoute
  AddCivilProtectionRoute: typeof AddCivilProtectionRoute
  AddDoctorRoute: typeof AddDoctorRoute
  AddDonorRoute: typeof AddDonorRoute
  AddEquipmentRoute: typeof AddEquipmentRoute
  AddHospitalRoute: typeof AddHospitalRoute
  AddLabRoute: typeof AddLabRoute
  AddOnCallPharmacyRoute: typeof AddOnCallPharmacyRoute
  AddPharmacyRoute: typeof AddPharmacyRoute
  AuthRoute: typeof AuthRoute
  CivilProtectionRoute: typeof CivilProtectionRoute
  DonorsRoute: typeof DonorsRoute
  EquipmentRoute: typeof EquipmentRoute
  HomeRoute: typeof HomeRoute
  HospitalsRoute: typeof HospitalsRoute
  MapRoute: typeof MapRoute
  NearbyDoctorsRoute: typeof NearbyDoctorsRoute
  NotificationsRoute: typeof NotificationsRoute
  OnCallPharmaciesRoute: typeof OnCallPharmaciesRoute
  OnboardingRoute: typeof OnboardingRoute
  PharmaciesRoute: typeof PharmaciesRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  DoctorsIdRoute: typeof DoctorsIdRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacies': {
      id: '/pharmacies'
      path: '/pharmacies'
      fullPath: '/pharmacies'
      preLoaderRoute: typeof PharmaciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/on-call-pharmacies': {
      id: '/on-call-pharmacies'
      path: '/on-call-pharmacies'
      fullPath: '/on-call-pharmacies'
      preLoaderRoute: typeof OnCallPharmaciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby-doctors': {
      id: '/nearby-doctors'
      path: '/nearby-doctors'
      fullPath: '/nearby-doctors'
      preLoaderRoute: typeof NearbyDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donors': {
      id: '/donors'
      path: '/donors'
      fullPath: '/donors'
      preLoaderRoute: typeof DonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/civil-protection': {
      id: '/civil-protection'
      path: '/civil-protection'
      fullPath: '/civil-protection'
      preLoaderRoute: typeof CivilProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-pharmacy': {
      id: '/add-pharmacy'
      path: '/add-pharmacy'
      fullPath: '/add-pharmacy'
      preLoaderRoute: typeof AddPharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-on-call-pharmacy': {
      id: '/add-on-call-pharmacy'
      path: '/add-on-call-pharmacy'
      fullPath: '/add-on-call-pharmacy'
      preLoaderRoute: typeof AddOnCallPharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-lab': {
      id: '/add-lab'
      path: '/add-lab'
      fullPath: '/add-lab'
      preLoaderRoute: typeof AddLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-hospital': {
      id: '/add-hospital'
      path: '/add-hospital'
      fullPath: '/add-hospital'
      preLoaderRoute: typeof AddHospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-equipment': {
      id: '/add-equipment'
      path: '/add-equipment'
      fullPath: '/add-equipment'
      preLoaderRoute: typeof AddEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-donor': {
      id: '/add-donor'
      path: '/add-donor'
      fullPath: '/add-donor'
      preLoaderRoute: typeof AddDonorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-doctor': {
      id: '/add-doctor'
      path: '/add-doctor'
      fullPath: '/add-doctor'
      preLoaderRoute: typeof AddDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-civil-protection': {
      id: '/add-civil-protection'
      path: '/add-civil-protection'
      fullPath: '/add-civil-protection'
      preLoaderRoute: typeof AddCivilProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-charity': {
      id: '/add-charity'
      path: '/add-charity'
      fullPath: '/add-charity'
      preLoaderRoute: typeof AddCharityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-blood-request': {
      id: '/add-blood-request'
      path: '/add-blood-request'
      fullPath: '/add-blood-request'
      preLoaderRoute: typeof AddBloodRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-ambulance': {
      id: '/add-ambulance'
      path: '/add-ambulance'
      fullPath: '/add-ambulance'
      preLoaderRoute: typeof AddAmbulanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacies/$id': {
      id: '/pharmacies/$id'
      path: '/$id'
      fullPath: '/pharmacies/$id'
      preLoaderRoute: typeof PharmaciesIdRouteImport
      parentRoute: typeof PharmaciesRoute
    }
    '/doctors/$id': {
      id: '/doctors/$id'
      path: '/doctors/$id'
      fullPath: '/doctors/$id'
      preLoaderRoute: typeof DoctorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/manage': {
      id: '/_authenticated/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof AuthenticatedManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage/': {
      id: '/_authenticated/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof AuthenticatedManageIndexRouteImport
      parentRoute: typeof AuthenticatedManageRoute
    }
    '/_authenticated/manage/submissions': {
      id: '/_authenticated/manage/submissions'
      path: '/submissions'
      fullPath: '/manage/submissions'
      preLoaderRoute: typeof AuthenticatedManageSubmissionsRouteImport
      parentRoute: typeof AuthenticatedManageRoute
    }
  }
}

interface AuthenticatedManageRouteChildren {
  AuthenticatedManageSubmissionsRoute: typeof AuthenticatedManageSubmissionsRoute
  AuthenticatedManageIndexRoute: typeof AuthenticatedManageIndexRoute
}

const AuthenticatedManageRouteChildren: AuthenticatedManageRouteChildren = {
  AuthenticatedManageSubmissionsRoute: AuthenticatedManageSubmissionsRoute,
  AuthenticatedManageIndexRoute: AuthenticatedManageIndexRoute,
}

const AuthenticatedManageRouteWithChildren =
  AuthenticatedManageRoute._addFileChildren(AuthenticatedManageRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedManageRoute: typeof AuthenticatedManageRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedManageRoute: AuthenticatedManageRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PharmaciesRouteChildren {
  PharmaciesIdRoute: typeof PharmaciesIdRoute
}

const PharmaciesRouteChildren: PharmaciesRouteChildren = {
  PharmaciesIdRoute: PharmaciesIdRoute,
}

const PharmaciesRouteWithChildren = PharmaciesRoute._addFileChildren(
  PharmaciesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AddRoute: AddRoute,
  AddAmbulanceRoute: AddAmbulanceRoute,
  AddBloodRequestRoute: AddBloodRequestRoute,
  AddCharityRoute: AddCharityRoute,
  AddCivilProtectionRoute: AddCivilProtectionRoute,
  AddDoctorRoute: AddDoctorRoute,
  AddDonorRoute: AddDonorRoute,
  AddEquipmentRoute: AddEquipmentRoute,
  AddHospitalRoute: AddHospitalRoute,
  AddLabRoute: AddLabRoute,
  AddOnCallPharmacyRoute: AddOnCallPharmacyRoute,
  AddPharmacyRoute: AddPharmacyRoute,
  AuthRoute: AuthRoute,
  CivilProtectionRoute: CivilProtectionRoute,
  DonorsRoute: DonorsRoute,
  EquipmentRoute: EquipmentRoute,
  HomeRoute: HomeRoute,
  HospitalsRoute: HospitalsRoute,
  MapRoute: MapRoute,
  NearbyDoctorsRoute: NearbyDoctorsRoute,
  NotificationsRoute: NotificationsRoute,
  OnCallPharmaciesRoute: OnCallPharmaciesRoute,
  OnboardingRoute: OnboardingRoute,
  PharmaciesRoute: PharmaciesRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  DoctorsIdRoute: DoctorsIdRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
